# Generated by Django 4.1.1 on 2022-09-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Tên')),
                ('age', models.IntegerField(verbose_name='Tuổi')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
            ],
        ),
    ]
