# Generated by Django 4.1.1 on 2022-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('age', models.IntegerField(verbose_name='Tuổi')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('hobby', models.TextField(verbose_name='Sở thích')),
            ],
        ),
    ]
